source 'git@github.com:mylcode/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MCWebSocket_Example' do
  pod 'MCWebSocket/DB', :path => '../'

  target 'MCWebSocket_Tests' do
    inherit! :search_paths

    
  end
end
