platform :ios, '8.0'

project '../MCWebSocket.xcodeproj'
workspace 'WebSocketExample.xcworkspace'

use_frameworks!
pod "CocoaAsyncSocket"

target 'MCWebSocket' do
end

target 'iOSExample' do
	project 'iOSExample/iOSExample.xcodeproj'
end
